#' Print Basic Information of an lbc_net Object
#'
#' @description Provides a concise summary of an lbc_net object, including sample size,
#' training loss, local balance (LSD) in training process, and key model hyperparameters.
#'
#' @param x An object of class "lbc_net", generated by lbc_net().
#' @param ... Additional arguments (ignored).
#'
#' @return Prints key training details and model parameters.
#'
#' @seealso \code{\link{summary}}, \code{\link{getLBC}}
#'
#' @examples
#' \dontrun{
#' model <- lbc_net(data = data, formula = Tr ~ X1 + X2 + X3 + X4)
#' print(model)  # Displays a concise overview
#' }
#'
#' @export
print.lbc_net <- function(x, ...) {
  if (!inherits(x, "lbc_net")) {
    stop("Error: object must be of class 'lbc_net'.")
  }

  # Extract key components
  formula          <- getLBC(x, "formula")
  Z                <- getLBC(x, "Z")
  Tr               <- getLBC(x, "Tr")
  loss             <- getLBC(x, "loss")
  lsd_train        <- getLBC(x, "lsd_train")
  parameters       <- getLBC(x, "parameters")
  stopping_criteria <- getLBC(x, "stopping_criteria")
  kernel           <- getLBC(x, "kernel")
  estimand_fit     <- if (!is.null(getLBC(x, "estimand"))) toupper(getLBC(x, "estimand")) else NA_character_
  ate_flag         <- if (!is.null(getLBC(x, "ate_flag"))) getLBC(x, "ate_flag") else NA
  has_effect       <- !is.null(getLBC(x, "effect"))

  # Compute sample characteristics
  sample_size <- nrow(Z)
  treated_size <- sum(Tr)
  control_size <- sample_size - treated_size

  # Convert ATE integer to descriptive string
  estimand_label <- switch(
    estimand_fit,
    "ATE" = "ATE (Average Treatment Effect)",
    "ATT" = "ATT (Average Treatment Effect on the Treated)",
    "mu1"   = "mu1 (Population Mean of the Treated Under Weights)",
    "mu0"   = "mu0 (Population Mean of the Control Under Weights)"
  )
  
  # Print concise overview
  if (!is.null(formula)) {
    cat("Call:", deparse(formula), "\n")
  }
  cat("Sample Size:", sample_size, " | Treated:", treated_size, " | Control:", control_size, "\n")
  cat("Estimand:", estimand_label, "\n\n")

  cat("--- Training Results ---\n")
  cat("Final Loss Value:", round(loss, 4), "\n")
  cat("Max LSD:", sprintf("%.2f%%", lsd_train$lsd_max), "\n")
  cat("Mean LSD:", sprintf("%.2f%%", lsd_train$lsd_mean), "\n\n")

  cat("--- Model Hyperparameters ---\n")
  cat(sprintf("Hidden Layers: %d | Hidden Units: %d\n", parameters$num_hidden_layers, parameters$hidden_dim))
  cat(sprintf("VAE Learning Rate: %.3f | LBC-Net Learning Rate: %.3f\n", parameters$vae_lr, parameters$lr))
  cat(sprintf("Weight Decay: %.1e | Balance Lambda: %.2f\n", parameters$weight_decay, parameters$balance_lambda))
  if (!is.null(kernel)) {
    cat("Kernel:", deparse(kernel), "\n")
  }
  cat("\n")

  cat("--- Stopping Criteria ---\n")
  cat(sprintf("LSD Threshold: %.2f%% | Rolling Window: %d\n", stopping_criteria$lsd_threshold, stopping_criteria$rolling_window))
  cat(sprintf("Max Training Epochs: %d\n", stopping_criteria$max_epochs))
  cat("\n")
  
  if (has_effect) {
    cat("--- Treatment Effect (stored in object) ---\n")
    cat(sprintf("Estimand: %s\n", estimand_label))
    cat(sprintf("Effect:   %.4f\n", getLBC(x, "effect")))
    cat(sprintf("SE:       %.4f\n", getLBC(x, "se")))
    cat(sprintf("95%% CI:   [%.4f, %.4f]\n",
                 unname(getLBC(x, "ci")["lower"]), unname(getLBC(x, "ci")["upper"])))
    cat("\n")
  }

  cat("Use summary(object) for a full model summary.\n")
}

#' Print an M-LBCNet Model
#'
#' @description Prints treatment sizes, joint-GPS training diagnostics,
#'   hyperparameters, stopping status, and outcome results when present. The
#'   reported training LSD is the primary treatment-versus-population
#'   diagnostic; full balance tables are available from \code{gsd(x)} and
#'   \code{lsd(x)}.
#' @param x An object of class \code{"m_lbcnet"}.
#' @param ... Additional arguments (currently ignored).
#' @return \code{x}, invisibly.
#' @examples
#' \dontrun{
#' fit <- m_lbcnet(Z = Z, Tr = Tr, max_epochs = 50)
#' print(fit)
#' }
#' @export
print.m_lbcnet <- function(x, ...) {
  if (!inherits(x, "m_lbcnet")) {
    stop("Error: object must be of class 'm_lbcnet'.")
  }
  group_sizes <- tabulate(x$Tr_code + 1L, nbins = x$n_treatments)
  names(group_sizes) <- as.character(x$treatment_levels)

  cat("M-LBCNet Model\n")
  cat("==============\n\n")
  cat("Call:\n")
  print(x$call)
  cat("\nSample Size:", nrow(x$Z), "\n")
  cat("Treatment Groups:", x$n_treatments, "\n\n")
  cat("Group Sizes:\n")
  for (index in seq_along(group_sizes)) {
    cat(" ", names(group_sizes)[index], ": ", group_sizes[index], "\n",
        sep = "")
  }

  cat("\n--- Training Results ---\n")
  cat("Final Loss:", format(x$loss, digits = 6), "\n")
  cat(
    "Treatment-vs-Population Max LSD:",
    sprintf("%.2f%%", x$lsd_train$lsd_max), "\n"
  )
  cat(
    "Treatment-vs-Population Mean LSD:",
    sprintf("%.2f%%", x$lsd_train$lsd_mean), "\n"
  )

  cat("\n--- Model Hyperparameters ---\n")
  cat("K:", x$K, "\n")
  cat("Kernel:", x$kernel, "\n")
  cat("Bandwidth Pilot:", x$bandwidth_pilot_method, "\n")
  cat("Hidden Layers:", x$parameters$num_hidden_layers, "\n")
  cat("Hidden Units:", x$parameters$hidden_dim, "\n")
  cat("Learning rates: VAE =", x$parameters$vae_lr,
      ", M-LBCNet =", x$parameters$lr, "\n")
  cat(sprintf("Weight Decay: %.1e\n", x$parameters$weight_decay))
  cat("Balance Lambda:", x$parameters$balance_lambda, "\n")
  cat("Epsilon:", x$parameters$epsilon, "\n")

  cat("\n--- Stopping Information ---\n")
  cat(
    "Epochs Run:", x$stopping_criteria$epochs_run,
    "of", x$stopping_criteria$max_epochs, "\n"
  )
  criterion_achieved <- isTRUE(x$stopping_criteria$early_stopping)
  cat(
    "LSD Criterion Achieved:",
    if (criterion_achieved) "Yes" else "No", "\n"
  )
  cat(
    "LSD Threshold:", sprintf("%.2f%%", x$stopping_criteria$lsd_threshold),
    "| Rolling Window:", x$stopping_criteria$rolling_window, "\n"
  )
  if (!criterion_achieved) {
    cat("Stopping Status: Maximum epochs reached; LSD criterion not achieved.\n")
  }

  if (!is.null(x$Y)) {
    cat("\n--- Treatment-Specific Marginal Means ---\n")
    print(x$means, row.names = FALSE)
    cat("\n--- Pairwise ATEs ---\n")
    print(x$pairwise_ate, row.names = FALSE)
  } else {
    cat("\nOnly the joint GPS model was fitted; no outcome was supplied.\n")
  }
  invisible(x)
}

#' Print Basic Information of an lsd Object
#'
#' @description Provides a concise summary of an lsd object for local balance (LSD).
#'
#' @param x An object of class "lsd", generated by lsd().
#' @param ... Additional arguments (ignored).
#'
#' @return Prints key training details and model parameters.
#'
#' @seealso \code{\link{summary}} and \code{\link{getLBC}}
#'
#' @examples
#' \dontrun{
#' model <- lbc_net(data = data, formula = Tr ~ X1 + X2 + X3 + X4)
#' lsd_fit <- lsd(model)
#' print(fit)  # Displays a concise overview
#' }
#'
#' @export
print.lsd <- function(x, ...) {
  if (!inherits(x, "lsd")) {
    stop("Error: object must be of class 'lsd'.")
  }

  # Extract key components
  Z <- getLBC(x, "Z")
  Tr <- getLBC(x, "Tr")
  LSD_mean <- getLBC(x, "LSD_mean")
  LSD_max <- getLBC(x, "LSD_max")
  kernel <- getLBC(x, "kernel")
  ATE <- getLBC(x, "ate_flag")

  # Compute sample characteristics
  sample_size <- nrow(Z)
  treated_size <- sum(Tr)
  control_size <- sample_size - treated_size

  # Convert ATE integer to descriptive string
  ATE_label <- if (ATE == 1) "ATE (Average Treatment Effect)" else "ATT (Average Treatment Effect on the Treated)"

  # Print concise overview
  cat("Sample Size:", sample_size, " | Treated:", treated_size, " | Control:", control_size, "\n")
  cat("Estimand:", ATE_label, "\n\n")

  cat(sprintf("--- Local Balance (LSD) %s ---\n", "%"))
  cat("Max LSD:", round(LSD_max, 4), "\n")
  cat("Mean LSD:", round(LSD_mean, 4), "\n\n")

  if (!is.null(kernel)) {
    cat("Kernel:", deparse(kernel), "\n")
  }
  cat("\n")
  cat("Use summary(object) for a full model summary.\n")

}

#' Print Basic Information of an lbc_net_surv Object
#'
#' @description
#' Provides a concise summary of an \code{"lbc_net_surv"} object, including sample size,
#' training loss, local balance (LSD) during training, key model hyperparameters, and
#' the estimated survival difference at a highlighted time point.
#'
#' @param x An object of class \code{"lbc_net_surv"}, generated by \code{\link{lbc_net_surv}}().
#' @param ... Additional arguments (ignored).
#'
#' @return Prints key training details, model parameters, and a brief summary of the
#' survival difference. Invisibly returns \code{x}.
#'
#' @seealso \code{\link{summary}}, \code{\link{getLBC}}, \code{\link{lbc_net_surv}}
#'
#' @examples
#' \dontrun{
#' fit_surv <- lbc_net_surv(
#'   data    = dat,
#'   formula = Tr ~ X1 + X2,
#'   time    = "time",
#'   delta   = "delta"
#' )
#' print(fit_surv)  # Displays a concise survival-focused overview
#' }
#'
#' @export
print.lbc_net_surv <- function(x, ...) {
  if (!inherits(x, "lbc_net_surv")) {
    stop("Error: object must be of class 'lbc_net_surv'.")
  }
  
  ## 1. Extract key components via getLBC()
  formula           <- getLBC(x, "formula")
  Z                 <- getLBC(x, "Z")
  Tr                <- getLBC(x, "Tr")
  loss              <- getLBC(x, "loss")
  lsd_train         <- getLBC(x, "lsd_train")
  parameters        <- getLBC(x, "parameters")
  stopping_criteria <- getLBC(x, "stopping_criteria")
  kernel            <- getLBC(x, "kernel")
  time_vec          <- getLBC(x, "time")
  delta_vec         <- getLBC(x, "delta")
  surv_obj          <- getLBC(x, "survival")
  
  ## 2. Sample characteristics
  sample_size  <- nrow(Z)
  treated_size <- sum(Tr)
  control_size <- sample_size - treated_size
  
  ## 3. Header and call
  cat("LBC-Net Survival Model (lbc_net_surv)\n")
  cat("=====================================\n")
  if (!is.null(formula)) {
    cat("Formula:", deparse(formula), "\n")
  }
  cat("Sample Size:", sample_size,
      " | Treated:", treated_size,
      " | Control:", control_size, "\n\n")
  
  ## 4. Training results
  cat("--- Training Results ---\n")
  cat("Final Loss Value:", round(loss, 4), "\n")
  cat("Max LSD:", sprintf("%.2f%%", lsd_train$lsd_max), "\n")
  cat("Mean LSD:", sprintf("%.2f%%", lsd_train$lsd_mean), "\n\n")
  
  ## 5. Model hyperparameters
  cat("--- Model Hyperparameters ---\n")
  cat(sprintf("Hidden Layers: %d | Hidden Units: %d\n",
              parameters$num_hidden_layers, parameters$hidden_dim))
  cat(sprintf("VAE Learning Rate: %.3f | LBC-Net Learning Rate: %.3f\n",
              parameters$vae_lr, parameters$lr))
  cat(sprintf("Weight Decay: %.1e | Balance Lambda: %.2f\n",
              parameters$weight_decay, parameters$balance_lambda))
  if (!is.null(kernel)) {
    cat("Kernel:", deparse(kernel), "\n")
  }
  cat("\n")
  
  ## 6. Stopping criteria
  cat("--- Stopping Criteria ---\n")
  cat(sprintf("LSD Threshold: %.2f%% | Rolling Window: %d\n",
              stopping_criteria$lsd_threshold, stopping_criteria$rolling_window))
  cat(sprintf("Max Training Epochs: %d\n", stopping_criteria$max_epochs))
  cat("\n")
  
  ## 7. Survival difference summary
  cat("--- Survival Difference ---\n")
  
  times   <- surv_obj$times
  diff    <- surv_obj$diff
  se_diff <- surv_obj$se_diff
  ci_l    <- surv_obj$ci_lower
  ci_u    <- surv_obj$ci_upper
    
  # Create a compact table of all results
  out_table <- data.frame(
    time     = times,
    S1       = surv_obj$S1,
    S0       = surv_obj$S0,
    diff     = diff,
    se       = se_diff,
    ci_lower = ci_l,
    ci_upper = ci_u
  )
  
  # Nicely formatted printing
  print(out_table, row.names = FALSE)
  
  cat("\nUse summary(object) for a full model summary.\n")
  
  invisible(x)
}

