#' Print Basic Information of an lbc_net Object
#'
#' @description Provides a concise summary of an lbc_net object, including sample size,
#' training loss, local balance (LSD) in training process, and key model hyperparameters.
#'
#' @param x An object of class "lbc_net", generated by lbc_net().
#' @param ... Additional arguments (ignored).
#'
#' @return Prints key training details and model parameters.
#'
#' @seealso \code{\link{summary}}, \code{\link{getLBC}}
#'
#' @examples
#' \dontrun{
#' model <- lbc_net(data = data, formula = Tr ~ X1 + X2 + X3 + X4)
#' print(model)  # Displays a concise overview
#' }
#'
#' @export
print.lbc_net <- function(x, ...) {
  if (!inherits(x, "lbc_net")) {
    stop("Error: object must be of class 'lbc_net'.")
  }

  # Extract key components
  formula <- getLBC(x, "formula")
  Z <- getLBC(x, "Z")
  Tr <- getLBC(x, "Tr")
  losses <- getLBC(x, "losses")
  lsd_train <- getLBC(x, "lsd_train")
  parameters <- getLBC(x, "parameters")
  stopping_criteria <- getLBC(x, "stopping_criteria")
  kernel <- getLBC(x, "kernel")
  ATE <- getLBC(x, "ATE")

  # Compute sample characteristics
  sample_size <- nrow(Z)
  treated_size <- sum(Tr)
  control_size <- sample_size - treated_size

  # Convert ATE integer to descriptive string
  ATE_label <- if (ATE == 1) "ATE (Average Treatment Effect)" else "ATT (Average Treatment Effect on the Treated)"

  # Print concise overview
  if (!is.null(formula)) {
    cat("Call:", deparse(formula), "\n")
  }
  cat("Sample Size:", sample_size, " | Treated:", treated_size, " | Control:", control_size, "\n")
  cat("Estimand:", ATE_label, "\n\n")

  cat("--- Training Results ---\n")
  cat("Final Loss Value:", round(losses$total_loss, 4), "\n")
  cat("Max LSD:", sprintf("%.2f%%", lsd_train$lsd_max), "\n")
  cat("Mean LSD:", sprintf("%.2f%%", lsd_train$lsd_mean), "\n\n")

  cat("--- Model Hyperparameters ---\n")
  cat(sprintf("Hidden Layers: %d | Hidden Units: %d\n", parameters$num_hidden_layers, parameters$hidden_dim))
  cat(sprintf("VAE Learning Rate: %.3f | LBC-Net Learning Rate: %.3f\n", parameters$vae_lr, parameters$lr))
  cat(sprintf("Weight Decay: %.1e | Balance Lambda: %.2f\n", parameters$weight_decay, parameters$balance_lambda))
  if (!is.null(kernel)) {
    cat("Kernel:", deparse(kernel), "\n")
  }
  cat("\n")

  cat("--- Stopping Criteria ---\n")
  cat(sprintf("LSD Threshold: %.2f%% | Rolling Window: %d\n", stopping_criteria$lsd_threshold, stopping_criteria$rolling_window))
  cat(sprintf("Max Training Epochs: %d\n", stopping_criteria$max_epochs))
  cat("\n")

  cat("Use summary(object) for a full model summary.\n")
}

#' Print Basic Information of an lsd Object
#'
#' @description Provides a concise summary of an lsd object for local balance (LSD).
#'
#' @param x An object of class "lsd", generated by lsd().
#' @param ... Additional arguments (ignored).
#'
#' @return Prints key training details and model parameters.
#'
#' @seealso \code{\link{summary}} and \code{\link{getLBC}}
#'
#' @examples
#' \dontrun{
#' model <- lbc_net(data = data, formula = Tr ~ X1 + X2 + X3 + X4)
#' lsd_fit <- lsd(model)
#' print(fit)  # Displays a concise overview
#' }
#'
#' @export
print.lsd <- function(x, ...) {
  if (!inherits(x, "lsd")) {
    stop("Error: object must be of class 'lsd'.")
  }

  # Extract key components
  Z <- getLBC(x, "Z")
  Tr <- getLBC(x, "Tr")
  LSD_mean <- getLBC(x, "LSD_mean")
  LSD_max <- getLBC(x, "LSD_max")
  kernel <- getLBC(x, "kernel")
  ATE <- getLBC(x, "ATE")

  # Compute sample characteristics
  sample_size <- nrow(Z)
  treated_size <- sum(Tr)
  control_size <- sample_size - treated_size

  # Convert ATE integer to descriptive string
  ATE_label <- if (ATE == 1) "ATE (Average Treatment Effect)" else "ATT (Average Treatment Effect on the Treated)"

  # Print concise overview
  cat("Sample Size:", sample_size, " | Treated:", treated_size, " | Control:", control_size, "\n")
  cat("Estimand:", ATE_label, "\n\n")

  cat(sprintf("--- Local Balance (LSD) %s ---\n", "%"))
  cat("Max LSD:", round(LSD_max, 4), "\n")
  cat("Mean LSD:", round(LSD_mean, 4), "\n\n")

  if (!is.null(kernel)) {
    cat("Kernel:", deparse(kernel), "\n")
  }
  cat("\n")
  cat("Use summary(object) for a full model summary.\n")

}
