#' Summary of an lbc_net Object
#'
#' @description Provides a structured summary of an `lbc_net` object,
#' including loss values, balance assessments, and (if available) a treatment
#' effect estimate with standard error and confidence interval.
#'
#' @param object An object of class `"lbc_net"`, generated by `lbc_net()`.
#' 
#' @param Y (Optional) A numeric vector of observed outcomes. If the model
#'   was originally fitted with an outcome `Y` inside \code{\link{lbc_net}}
#'   and already contains a stored treatment effect (and variance), this
#'   argument is ignored and the stored results are reported. If no treatment
#'   effect is stored in `object` and `Y` is supplied, a point estimate is
#'   computed via \code{\link{est_effect}} without a variance estimate.
#'
#' @param type A character string specifying the treatment effect to estimate
#'   when using \code{\link{est_effect}}. Options:
#'   - `"mu1"`: Computes the weighted mean outcome for Tr = 1.
#'   - `"mu0"`: Computes the weighted mean outcome for Tr = 0.
#'   - `"ATE"` (default): Computes the Average Treatment Effect.
#'   - `"ATT"`: Computes the Average Treatment Effect on the Treated.
#'   If the model already stores a treatment effect (from a call to
#'   \code{lbc_net(..., Y = ..., estimand = ...)}), the stored type is used
#'   instead of this argument.
#'   
#' @param ... Additional arguments (ignored).
#'
#' @return A list containing:
#' \describe{
#'   \item{\code{sample_info}}{Sample sizes and covariate counts.}
#'   \item{\code{losses}}{Training losses.}
#'   \item{\code{local_balance}}{Local standardized differences from training.}
#'   \item{\code{balance_table}}{Pre- and post-weighting global standardized differences (GSD).}
#'   \item{\code{treatment_effect}}{Estimated treatment effect and, when available,
#'     its standard error and confidence interval.}
#'   \item{\code{gsd}}{GSD after weighting.}
#'   \item{\code{hypothesis_test}}{Stored global and pairwise ATE hypothesis
#'     tests, when this component is present in the fitted object.}
#' }
#'
#' @details
#' The function extracts key model components using \code{\link{getLBC}}.
#' If the fitted object contains a stored treatment effect (e.g., from a call
#' to \code{lbc_net(..., Y = ..., estimand = ..., compute_variance = TRUE)}),
#' \code{summary.lbc_net} reports that estimate together with its standard
#' error and 95\% confidence interval.
#' 
#' If no treatment effect is stored and `Y` is supplied, \code{est_effect}
#' is used to compute a point estimate only (no variance). If neither is
#' available, the summary focuses on balance diagnostics.
#'
#' Stored \code{hypothesis_test} results from \code{\link{hypo_test}} are
#' printed and included in the returned list without recomputation. If the
#' stored component is \code{NULL}, it is retained without printing tests.
#'
#' It is designed for estimating causal effects in settings with continuous or
#' binary outcomes. For survival outcomes, users should apply appropriate
#' survival analysis models, such as a weighted Cox model or other
#' time-to-event estimation methods.
#'
#' @seealso \code{\link{est_effect}}, \code{\link{gsd}}, \code{\link{getLBC}}
#'
#' @examples
#' \dontrun{
#' model <- lbc_net(data = data, formula = Tr ~ X1 + X2 + X3 + X4)
#' summary(model)  # Summary without treatment effect estimation
#' summary(model, Y = my_outcome, type = "ATE")  # Summary including treatment effect
#' 
#' out <- summary(model)
#' names(out)
#' out$balance_table
#' }
#'
#' @export
summary.lbc_net <- function(object, Y = NULL, type = "ATE", ...) {

  if (is.null(object) || !inherits(object, "lbc_net")) {
    stop("Error: `object` must be an object of class 'lbc_net'.")
  }
  
  loss      <- getLBC(object, "loss")
  lsd_train <- getLBC(object, "lsd_train")
  formula   <- getLBC(object, "formula")
  Z         <- getLBC(object, "Z")
  Tr        <- getLBC(object, "Tr")
  
  estimand_fit <- if (!is.null(getLBC(object, "estimand"))) toupper(getLBC(object, "estimand")) else NA_character_
  ate_flag     <- if (!is.null(getLBC(object, "ate_flag"))) getLBC(object, "ate_flag") else NA

  # Compute sample characteristics
  sample_size <- nrow(Z)
  num_covariates <- ncol(Z)

  # Compute treatment group sizes
  treated_size <- sum(Tr)
  control_size <- sample_size - treated_size

  # Compute pre-weighting GSD (weights = 1 for all observations)
  gsd_values_before <- gsd(Z = Z, Tr = Tr, wt = rep(1, sample_size))
  
  # Compute global standardized difference (GSD) if requested
  gsd_values_after <- gsd(object)
  
  # Combine into a table
  balance_table <- data.frame(
    Covariate = names(gsd_values_after),
    Pre_Weighting_GSD = as.numeric(gsd_values_before),
    Post_Weighting_GSD = as.numeric(gsd_values_after)
  )
  
  # Compute treatment effect if Y is provided
  # Try to pull a stored treatment effect (Python-based, with variance)
  has_stored_effect <- !is.null(getLBC(object, "effect"))
  effect_label <- NULL
  effect       <- NULL
  se_val       <- NULL
  ci_lower     <- NULL
  ci_upper     <- NULL
  
  if (has_stored_effect) {
    # Use effect, se, ci stored in the object (Python-based, preferred)
    effect_label <- if (!is.na(estimand_fit)) estimand_fit else "ATE"
    effect       <- getLBC(object, "effect")
    se_val       <- getLBC(object, "se")
    ci_lower     <- unname(getLBC(object, "ci")["lower"])
    ci_upper     <- unname(getLBC(object, "ci")["upper"])
    
  } else if (!is.null(Y)) {
    effect_label <- toupper(type)
    effect       <- est_effect(object, Y, type = type)
    # se/CI not available in this mode
  }

  # Print Summary
  # Format formula output
  formula_text <- deparse(formula, width.cutoff = 60)

  # Print Summary
  cat("Call:\n", formula_text, "\n")
  cat("Sample Size:", sample_size, " | Number of Covariates:", num_covariates, "\n")
  cat("Treated:", treated_size, " | Control:", control_size, "\n\n")

  cat("--- Losses ---\n")
  cat(sprintf("Total Loss: %.4f\n\n", loss))

  cat(sprintf("--- Local Balance (LSD) %s ---\n", "%"))
  cat(sprintf("Max LSD:   %.4f\n", lsd_train$lsd_max))
  cat(sprintf("Mean LSD:  %.4f\n\n", lsd_train$lsd_mean))
  
  cat(sprintf("--- Global Standardized Differences (GSD) %s ---\n", "%"))
  
  # Format for printing
  cov_names <- format(balance_table$Covariate, width = max(nchar(balance_table$Covariate)) + 2, justify = "left")
  pre_gsd_fmt <- format(sprintf("%.4f", balance_table$Pre_Weighting_GSD), width = 12, justify = "right")
  post_gsd_fmt <- format(sprintf("%.4f", balance_table$Post_Weighting_GSD), width = 12, justify = "right")
  
  # Header row
  cat(format("Covariate", width = max(nchar(balance_table$Covariate)) + 2, justify = "left"),
      format("Pre-GSD", width = 12, justify = "right"),
      format("Post-GSD", width = 12, justify = "right"), "\n")
  
  cat(strrep("-", max(nchar(balance_table$Covariate)) + 30), "\n")
  
  # Print each row
  for (i in seq_along(cov_names)) {
    cat(cov_names[i], pre_gsd_fmt[i], post_gsd_fmt[i], "\n")
  }
  cat("\n")

  cat("--- Treatment Effect Estimate ---\n")
  if (has_stored_effect && !is.null(effect)) {
    # Stored effect from Python path
    cat(sprintf("%s: %.4f", effect_label, effect))
    if (!is.null(se_val)) {
      cat(sprintf("  (SE: %.4f)", se_val))
    }
    if (!is.null(ci_lower) && !is.null(ci_upper)) {
      cat(sprintf("  95%% CI: [%.4f, %.4f]", ci_lower, ci_upper))
    }
    cat("\n")
  } else if (!is.null(effect)) {
    # R-based est_effect point estimate
    cat(sprintf("%s: %.4f (no variance estimate; computed via est_effect)\n",
                effect_label, effect))
  } else {
    cat("Effect estimate not calculated. Provide `Y` to compute a point estimate,\n")
    cat("or fit the model with `Y` inside `lbc_net()` to obtain effect and variance.\n")
  }
  
  # Return object
  summary_list <- list(
    sample_info = list(
      sample_size    = sample_size,
      treated_size   = treated_size,
      control_size   = control_size,
      num_covariates = num_covariates
    ),
    loss = loss,
    local_balance = list(
      lsd_max  = lsd_train$lsd_max,
      lsd_mean = lsd_train$lsd_mean
    ),
    balance_table    = balance_table,
    treatment_effect = if (!is.null(effect)) {
      list(
        type     = effect_label,
        estimate = effect,
        se       = se_val,
        ci_lower = ci_lower,
        ci_upper = ci_upper
      )
    } else {
      NULL
    },
    gsd = gsd_values_after
  )
  
  if ("hypothesis_test" %in% names(object)) {
    summary_list["hypothesis_test"] <- object["hypothesis_test"]
  }
  if (!is.null(summary_list$hypothesis_test)) {
    cat("\n--- ATE Hypothesis Tests ---\n")
    cat("Global Wald Test:\n")
    print(summary_list$hypothesis_test$global, row.names = FALSE)
    cat("\nPairwise Tests:\n")
    print(summary_list$hypothesis_test$pairwise, row.names = FALSE)
  }

  invisible(summary_list)

}


.m_lbcnet_metric_summary <- function(data, value_name, group_names) {
  values <- data[[value_name]]
  groups <- unique(data[group_names])
  group_max <- numeric(nrow(groups))
  group_mean <- numeric(nrow(groups))
  for (group_index in seq_len(nrow(groups))) {
    selected <- rep(TRUE, nrow(data))
    for (group_name in group_names) {
      selected <- selected &
        data[[group_name]] == groups[[group_name]][group_index]
    }
    group_max[group_index] <- max(values[selected])
    group_mean[group_index] <- mean(values[selected])
  }
  groups$max <- group_max
  groups$mean <- group_mean
  list(
    max = max(values),
    mean = mean(values),
    by_group = groups
  )
}


#' Summarize an M-LBCNet Model
#'
#' @description Provides a structured M-LBCNet summary with sample and training
#'   information, generalized propensity-score and observed-weight summaries,
#'   outcome inference when available, and concise global and local balance
#'   summaries.
#' @param object An object of class \code{"m_lbcnet"}.
#' @param ... Additional arguments (currently ignored).
#' @return Invisibly returns a structured list. The list retains the fitted
#'   model summaries and contains the complete derived diagnostics in
#'   \code{gsd} and \code{lsd}; only concise maxima, means, and grouped
#'   balance summaries are printed. The stored \code{hypothesis_test}
#'   component is also included when present in the fitted object.
#' @details \code{summary.m_lbcnet()} computes \code{gsd(object)} and
#'   \code{lsd(object)} on demand. In each diagnostic, \code{versus_population}
#'   is primary because it follows the M-LBCNet treatment-versus-population
#'   balance targets. \code{pairwise} is secondary. Pairwise LSD compares both
#'   treatments inside one common neighborhood defined by the reported
#'   localizing treatment's GPS component.
#'
#'   Stored global and pairwise ATE \code{hypothesis_test} results from
#'   \code{\link{hypo_test}} are printed without recomputation. If the stored
#'   component is \code{NULL}, it is retained without printing tests.
#' @examples
#' \dontrun{
#' fit <- m_lbcnet(Z = Z, Tr = Tr, max_epochs = 50)
#' out <- summary(fit)
#' out$gsd$versus_population
#' out$lsd$pairwise
#' }
#' @export
summary.m_lbcnet <- function(object, ...) {
  if (!inherits(object, "m_lbcnet")) {
    stop("Error: 'object' must be an object of class 'm_lbcnet'.")
  }
  group_sizes <- tabulate(
    object$Tr_code + 1L, nbins = object$n_treatments
  )
  names(group_sizes) <- as.character(object$treatment_levels)
  gps_summary <- t(vapply(
    seq_len(object$n_treatments),
    function(index) {
      values <- object$fitted.values[, index]
      c(
        min = min(values),
        Q1 = unname(stats::quantile(values, 0.25)),
        median = stats::median(values),
        mean = mean(values),
        Q3 = unname(stats::quantile(values, 0.75)),
        max = max(values)
      )
    },
    numeric(6)
  ))
  rownames(gps_summary) <- as.character(object$treatment_levels)
  weight_summary <- summary(object$weights)

  gsd_result <- gsd(object)
  lsd_result <- lsd(object)
  global_balance <- list(
    versus_population = .m_lbcnet_metric_summary(
      gsd_result$versus_population, "gsd", "treatment"
    ),
    pairwise = .m_lbcnet_metric_summary(
      gsd_result$pairwise, "gsd", c("treatment_1", "treatment_2")
    )
  )
  local_balance <- list(
    versus_population = .m_lbcnet_metric_summary(
      lsd_result$versus_population, "lsd", "treatment"
    ),
    pairwise = .m_lbcnet_metric_summary(
      lsd_result$pairwise, "lsd",
      c("localizing_treatment", "treatment_1", "treatment_2")
    )
  )

  result <- list(
    call = object$call,
    sample_size = nrow(object$Z),
    covariate_count = ncol(object$Z),
    treatment_count = object$n_treatments,
    treatment_group_sizes = group_sizes,
    bandwidth_pilot_method = object$bandwidth_pilot_method,
    loss = object$loss,
    max_lsd = object$lsd_train$lsd_max,
    mean_lsd = object$lsd_train$lsd_mean,
    lsd_by_treatment = object$lsd_train$lsd_by_treatment,
    gps_summary = gps_summary,
    observed_ipw_summary = weight_summary,
    means = object$means,
    pairwise_ate = object$pairwise_ate,
    covariance = object$covariance,
    global_balance = global_balance,
    local_balance = local_balance,
    gsd = gsd_result,
    lsd = lsd_result
  )

  cat("M-LBCNet Model Summary\n")
  cat("======================\n\n")
  cat("Call:\n")
  print(result$call)
  cat("\nSample Size:", result$sample_size, "\n")
  cat("Number of Covariates:", result$covariate_count, "\n")
  cat("Number of Treatments:", result$treatment_count, "\n\n")
  cat("Bandwidth Pilot:", result$bandwidth_pilot_method, "\n\n")
  cat("Treatment Group Sizes:\n")
  print(result$treatment_group_sizes)
  cat("\nTraining Loss:", format(result$loss, digits = 6), "\n")
  cat(
    "Training Treatment-vs-Population Max LSD:",
    sprintf("%.4f", result$max_lsd), "\n"
  )
  cat(
    "Training Treatment-vs-Population Mean LSD:",
    sprintf("%.4f", result$mean_lsd), "\n"
  )

  cat("\nGlobal Balance:\n")
  cat(sprintf(
    " Treatment vs population: max GSD = %.4f, mean GSD = %.4f\n",
    result$global_balance$versus_population$max,
    result$global_balance$versus_population$mean
  ))
  cat(sprintf(
    " Pairwise: max GSD = %.4f, mean GSD = %.4f\n",
    result$global_balance$pairwise$max,
    result$global_balance$pairwise$mean
  ))
  cat("\nGlobal Treatment-vs-Population GSD by Treatment:\n")
  print(result$global_balance$versus_population$by_group, row.names = FALSE)

  cat("\nLocal Balance:\n")
  cat(sprintf(
    " Treatment vs population: max LSD = %.4f, mean LSD = %.4f\n",
    result$local_balance$versus_population$max,
    result$local_balance$versus_population$mean
  ))
  cat(sprintf(
    " Pairwise: max LSD = %.4f, mean LSD = %.4f\n",
    result$local_balance$pairwise$max,
    result$local_balance$pairwise$mean
  ))
  cat("\nLocal Treatment-vs-Population LSD by Treatment:\n")
  print(result$local_balance$versus_population$by_group, row.names = FALSE)

  cat("\nGPS Summary by Treatment:\n")
  print(result$gps_summary)
  cat("\nObserved ATE IPW Summary:\n")
  print(result$observed_ipw_summary)
  if (!is.null(object$Y)) {
    cat("\nTreatment-Specific Marginal Means:\n")
    print(result$means, row.names = FALSE)
    cat("\nPairwise ATEs:\n")
    print(result$pairwise_ate, row.names = FALSE)
  } else {
    cat("\nNo outcome supplied; means and pairwise ATEs were not estimated.\n")
  }
  if ("hypothesis_test" %in% names(object)) {
    result["hypothesis_test"] <- object["hypothesis_test"]
  }
  if (!is.null(result$hypothesis_test)) {
    cat("\n--- ATE Hypothesis Tests ---\n")
    cat("Global Wald Test:\n")
    print(result$hypothesis_test$global, row.names = FALSE)
    cat("\nPairwise Tests:\n")
    print(result$hypothesis_test$pairwise, row.names = FALSE)
  }
  invisible(result)
}

#' Summary of an lsd Object
#'
#' @description Provides a structured summary of an `lsd` object.
#'
#' @param object An object of class `"lsd"`, generated by `lsd()`.
#' @param ... Additional arguments passed to the specific method.
#'
#' @return A structured summary of the `lbc_net` object, including:
#' \itemize{
#'   \item Average local balance over all cks for each covariate.
#'   \item Local balance summary: `lsd_max`, `lsd_mean` for local standardized mean difference calculated during training.
#'   \item Sample characteristics: `sample_size`, `num_covariates`, `treated_size`, `control_size`.
#' }
#'
#' @details
#' The function extracts key model components using \code{\link{getLBC}}.
#'
#' @seealso \code{\link{getLBC}}
#'
#' @examples
#' \dontrun{
#' model <- lbc_net(data = data, formula = Tr ~ X1 + X2 + X3 + X4)
#' lsd_result <- lsd(model)
#' summary(lsd_result)
#' }
#'
#' @importFrom stats formula
#' @importFrom dplyr %>%
#' @export
summary.lsd <- function(object, ...) {
  if (!inherits(object, "lsd")) {
    stop("Error: `object` must be of class 'lsd'.")
  }

  # Extract key components using getLBC()
  LSD_mean <- getLBC(object, "LSD_mean")
  LSD_max <- getLBC(object, "LSD_max")
  LSD <- getLBC(object, "LSD")
  Z <- getLBC(object, "Z")
  Tr <- getLBC(object, "Tr")
  ATE <- getLBC(object, "ate_flag")

  # Compute sample characteristics
  sample_size <- nrow(Z)
  num_covariates <- ncol(Z)

  # Compute treatment group sizes
  treated_size <- sum(Tr)
  control_size <- sample_size - treated_size

  # Convert ATE integer to descriptive string
  ATE_label <- if (ATE == 1) "ATE (Average Treatment Effect)" else "ATT (Average Treatment Effect on the Treated)"

  # Print Summary
  # Format formula output
  formula_text <- deparse(formula, width.cutoff = 60)

  # Print Summary
  cat("Call:\n", formula_text, "\n")
  cat("Sample Size:", sample_size, " | Number of Covariates:", num_covariates, "\n")
  cat("Treated:", treated_size, " | Control:", control_size, "\n")
  cat("Estimand:", ATE_label, "\n\n")

  cat(sprintf("--- Local Balance (LSD) %s ---\n", "%"))
  cat(sprintf("Max LSD:   %.4f\n", LSD_max))
  cat(sprintf("Mean LSD:  %.4f\n\n", LSD_mean))

  # Convert LSD named vector to a dataframe
  lsd_df <- data.frame(
    Covariate = if (!is.null(colnames(LSD))) {
      colnames(LSD)
    } else {
      paste0("Z", seq_len(ncol(LSD)))  # Generate Z1, Z2, ..., Zp if colnames are NULL
    },
    LSD = sprintf("%.4f", as.numeric(colMeans(LSD)))
  )

  # Define column width for alignment
  max_name_length <- max(nchar(lsd_df$Covariate)) + 2  # Adjust spacing
  formatted_covariate <- format(lsd_df$Covariate, width = max_name_length, justify = "left")
  formatted_lsd <- format(lsd_df$LSD, width = 7, justify = "right")

  cat(format("Covariates", width = max_name_length, justify = "left"),
      format("LSD %", width = 7, justify = "right"), "\n")
  cat(strrep("-", max_name_length + 9), "\n")

  # Print table with proper alignment
  for (i in seq_along(formatted_covariate)) {
    cat(formatted_covariate[i], formatted_lsd[i], "\n")
  }

  cat("\n")

}

#' Summary of an lbc_net_surv Object
#'
#' @description
#' Provides a structured summary of an \code{"lbc_net_surv"} object,
#' including training loss, balance assessments, and the estimated survival
#' difference with standard error and confidence interval at a grid of time
#' points.
#'
#' @param object An object of class \code{"lbc_net_surv"}, generated by
#'   \code{\link{lbc_net_surv}}().
#' @param ... Additional arguments (ignored).
#'
#' @return A list containing:
#' \describe{
#'   \item{\code{sample_info}}{Sample sizes and covariate counts.}
#'   \item{\code{loss}}{Training loss.}
#'   \item{\code{local_balance}}{Local standardized differences (LSD) from training.}
#'   \item{\code{balance_table}}{Pre- and post-weighting global standardized
#'         differences (GSD).}
#'   \item{\code{survival}}{Estimated survival curves \eqn{S_1(t)}, \eqn{S_0(t)},
#'         survival difference, standard errors, and confidence intervals on
#'         the evaluation grid.}
#'   \item{\code{gsd}}{GSD after weighting.}
#' }
#'
#' @details
#' The function extracts key model components using \code{\link{getLBC}} from
#' the fitted object. It reports:
#' \itemize{
#'   \item Sample size and covariate dimensions;
#'   \item Training loss and local balance diagnostics (LSD);
#'   \item Global standardized differences (GSD) before and after weighting;
#'   \item The estimated survival difference \eqn{\Delta(t) = S_1(t) - S_0(t)}
#'         over the evaluation time grid, including standard errors and
#'         Wald 95\% confidence intervals.
#' }
#'
#' This method is specifically designed for survival outcomes fitted via
#' \code{\link{lbc_net_surv}}. For non-survival outcomes, use
#' \code{\link{summary.lbc_net}} instead.
#'
#' @seealso \code{\link{lbc_net_surv}}, \code{\link{gsd}}, \code{\link{getLBC}}
#'
#' @examples
#' \dontrun{
#'   fit_surv <- lbc_net_surv(
#'     data    = dat,
#'     formula = Tr ~ X1 + X2,
#'     time    = "time",
#'     delta   = "delta"
#'   )
#'   out <- summary(fit_surv)
#'   names(out)
#'   head(out$survival$survival_df)
#' }
#'
#' @export
summary.lbc_net_surv <- function(object, ...) {
  
  if (is.null(object) || !inherits(object, "lbc_net_surv")) {
    stop("Error: `object` must be an object of class 'lbc_net_surv'.")
  }
  
  ## 1. Extract main components via getLBC()
  loss      <- getLBC(object, "loss")
  lsd_train <- getLBC(object, "lsd_train")
  formula   <- getLBC(object, "formula")
  Z         <- getLBC(object, "Z")
  Tr        <- getLBC(object, "Tr")
  
  surv_obj <- getLBC(object, "survival")
  
  times    <- surv_obj$times
  S1       <- surv_obj$S1
  S0       <- surv_obj$S0
  diff     <- surv_obj$diff
  se_diff  <- surv_obj$se_diff
  ci_lower <- surv_obj$ci_lower
  ci_upper <- surv_obj$ci_upper
  
  ## 2. Sample characteristics
  sample_size    <- nrow(Z)
  num_covariates <- ncol(Z)
  treated_size   <- sum(Tr)
  control_size   <- sample_size - treated_size
  
  ## 3. GSD: before (weights = 1) and after weighting
  gsd_values_before <- gsd(Z = Z, Tr = Tr, wt = rep(1, sample_size))
  gsd_values_after  <- gsd(object)
  
  balance_table <- data.frame(
    Covariate          = names(gsd_values_after),
    Pre_Weighting_GSD  = as.numeric(gsd_values_before),
    Post_Weighting_GSD = as.numeric(gsd_values_after),
    row.names = NULL
  )
  
  ## --- Printing section ---
  
  formula_text <- deparse(formula, width.cutoff = 60)
  
  cat("Call:\n", formula_text, "\n")
  cat("Sample Size:", sample_size,
      "| Number of Covariates:", num_covariates, "\n")
  cat("Treated:", treated_size, "| Control:", control_size, "\n\n")
  
  cat("--- Loss ---\n")
  cat(sprintf("Total Loss: %.4f\n\n", loss))
  
  cat(sprintf("--- Local Balance (LSD) %s ---\n", "%"))
  cat(sprintf("Max LSD:   %.4f\n", lsd_train$lsd_max))
  cat(sprintf("Mean LSD:  %.4f\n\n", lsd_train$lsd_mean))
  
  cat(sprintf("--- Global Standardized Differences (GSD) %s ---\n", "%"))
  
  # Formatting for printing balance table
  cov_width   <- max(nchar(balance_table$Covariate))
  cov_names   <- format(balance_table$Covariate,
                        width = cov_width + 2, justify = "left")
  pre_gsd_fmt  <- format(sprintf("%.4f", balance_table$Pre_Weighting_GSD),
                         width = 12, justify = "right")
  post_gsd_fmt <- format(sprintf("%.4f", balance_table$Post_Weighting_GSD),
                         width = 12, justify = "right")
  
  # Header
  cat(format("Covariate",
             width = cov_width + 2, justify = "left"),
      format("Pre-GSD", width = 12, justify = "right"),
      format("Post-GSD", width = 12, justify = "right"),
      "\n")
  
  cat(strrep("-", cov_width + 30), "\n")
  
  # Rows
  for (i in seq_along(cov_names)) {
    cat(cov_names[i], pre_gsd_fmt[i], post_gsd_fmt[i], "\n")
  }
  cat("\n")
  
  ## --- Survival difference summary ---
  
  cat("--- Survival Difference Delta(t) = S1(t) - S0(t) ---\n")
  
  # Table of grid points
  n_grid <- length(times)
  cat("\nGrid of evaluation times:\n")
  if (n_grid <= 10L) {
    show_idx <- seq_len(n_grid)
  } else {
    show_idx <- seq_len(10L)
  }
  
  surv_tab_show <- data.frame(
    time    = times[show_idx],
    S1      = S1[show_idx],
    S0      = S0[show_idx],
    diff    = diff[show_idx],
    se      = se_diff[show_idx],
    ci_low  = ci_lower[show_idx],
    ci_high = ci_upper[show_idx]
  )
  
  print(surv_tab_show, row.names = FALSE)
  if (n_grid > 10L) {
    cat("... (showing first 10 of", n_grid, "time points)\n")
  }
  
  ## --- Return structured list ---
  
  survival_df <- data.frame(
    time    = times,
    S1      = S1,
    S0      = S0,
    diff    = diff,
    se      = se_diff,
    ci_low  = ci_lower,
    ci_high = ci_upper
  )
  
  summary_list <- list(
    sample_info = list(
      sample_size    = sample_size,
      treated_size   = treated_size,
      control_size   = control_size,
      num_covariates = num_covariates
    ),
    loss = loss,
    local_balance = list(
      lsd_max  = lsd_train$lsd_max,
      lsd_mean = lsd_train$lsd_mean
    ),
    balance_table = balance_table,
    survival = survival_df,
    gsd = gsd_values_after
  )
  
  invisible(summary_list)
}

