#' Summary of an lbc_net Object
#'
#' @description Provides a structured summary of an `lbc_net` object,
#' including loss values, balance assessments, and (if available) a treatment
#' effect estimate with standard error and confidence interval.
#'
#' @param object An object of class `"lbc_net"`, generated by `lbc_net()`.
#' 
#' @param Y (Optional) A numeric vector of observed outcomes. If the model
#'   was originally fitted with an outcome `Y` inside \code{\link{lbc_net}}
#'   and already contains a stored treatment effect (and variance), this
#'   argument is ignored and the stored results are reported. If no treatment
#'   effect is stored in `object` and `Y` is supplied, a point estimate is
#'   computed via \code{\link{est_effect}} without a variance estimate.
#'
#' @param type A character string specifying the treatment effect to estimate
#'   when using \code{\link{est_effect}}. Options:
#'   - `"Y"`: Computes the weighted mean outcome.
#'   - `"ATE"` (default): Computes the Average Treatment Effect.
#'   - `"ATT"`: Computes the Average Treatment Effect on the Treated.
#'   If the model already stores a treatment effect (from a call to
#'   \code{lbc_net(..., Y = ..., estimand = ...)}), the stored type is used
#'   instead of this argument.
#'   
#' @param ... Additional arguments (ignored).
#'
#' @return A list containing:
#' \describe{
#'   \item{\code{sample_info}}{Sample sizes and covariate counts.}
#'   \item{\code{losses}}{Training losses.}
#'   \item{\code{local_balance}}{Local standardized differences from training.}
#'   \item{\code{balance_table}}{Pre- and post-weighting global standardized differences (GSD).}
#'   \item{\code{treatment_effect}}{Estimated treatment effect and, when available,
#'     its standard error and confidence interval.}
#'   \item{\code{gsd}}{GSD after weighting.}
#' }
#'
#' @details
#' The function extracts key model components using \code{\link{getLBC}}.
#' If the fitted object contains a stored treatment effect (e.g., from a call
#' to \code{lbc_net(..., Y = ..., estimand = ..., compute_variance = TRUE)}),
#' \code{summary.lbc_net} reports that estimate together with its standard
#' error and 95\% confidence interval.
#' 
#' If no treatment effect is stored and `Y` is supplied, \code{est_effect}
#' is used to compute a point estimate only (no variance). If neither is
#' available, the summary focuses on balance diagnostics.
#'
#' It is designed for estimating causal effects in settings with continuous or
#' binary outcomes. For survival outcomes, users should apply appropriate
#' survival analysis models, such as a weighted Cox model or other
#' time-to-event estimation methods.
#'
#' @seealso \code{\link{est_effect}}, \code{\link{gsd}}, \code{\link{getLBC}}
#'
#' @examples
#' \dontrun{
#' model <- lbc_net(data = data, formula = Tr ~ X1 + X2 + X3 + X4)
#' summary(model)  # Summary without treatment effect estimation
#' summary(model, Y = my_outcome, type = "ATE")  # Summary including treatment effect
#' 
#' out <- summary(model)
#' names(out)
#' out$balance_table
#' }
#'
#' @export
summary.lbc_net <- function(object, Y = NULL, type = "ATE", ...) {

  if (is.null(object) || !inherits(object, "lbc_net")) {
    stop("Error: `object` must be an object of class 'lbc_net'.")
  }
  
  loss      <- getLBC(object, "loss")
  lsd_train <- getLBC(object, "lsd_train")
  formula   <- getLBC(object, "formula")
  Z         <- getLBC(object, "Z")
  Tr        <- getLBC(object, "Tr")
  
  estimand_fit <- if (!is.null(getLBC(object, "estimand"))) toupper(getLBC(object, "estimand")) else NA_character_
  ate_flag     <- if (!is.null(getLBC(object, "ate_flag"))) getLBC(object, "ate_flag") else NA

  # Compute sample characteristics
  sample_size <- nrow(Z)
  num_covariates <- ncol(Z)

  # Compute treatment group sizes
  treated_size <- sum(Tr)
  control_size <- sample_size - treated_size

  # Compute pre-weighting GSD (weights = 1 for all observations)
  gsd_values_before <- gsd(Z = Z, Tr = Tr, wt = rep(1, sample_size))
  
  # Compute global standardized difference (GSD) if requested
  gsd_values_after <- gsd(object)
  
  # Combine into a table
  balance_table <- data.frame(
    Covariate = names(gsd_values_after),
    Pre_Weighting_GSD = as.numeric(gsd_values_before),
    Post_Weighting_GSD = as.numeric(gsd_values_after)
  )
  
  # Compute treatment effect if Y is provided
  # Try to pull a stored treatment effect (Python-based, with variance)
  has_stored_effect <- !is.null(getLBC(object, "effect"))
  effect_label <- NULL
  effect       <- NULL
  se_val       <- NULL
  ci_lower     <- NULL
  ci_upper     <- NULL
  
  if (has_stored_effect) {
    # Use effect, se, ci stored in the object (Python-based, preferred)
    effect_label <- if (!is.na(estimand_fit)) estimand_fit else "ATE"
    effect       <- getLBC(object, "effect")
    se_val       <- getLBC(object, "se")
    ci_lower     <- unname(getLBC(object, "ci")["lower"])
    ci_upper     <- unname(getLBC(object, "ci")["upper"])
    
  } else if (!is.null(Y)) {
    effect_label <- toupper(type)
    effect       <- est_effect(object, Y, type = type)
    # se/CI not available in this mode
  }

  # Print Summary
  # Format formula output
  formula_text <- deparse(formula, width.cutoff = 60)

  # Print Summary
  cat("Call:\n", formula_text, "\n")
  cat("Sample Size:", sample_size, " | Number of Covariates:", num_covariates, "\n")
  cat("Treated:", treated_size, " | Control:", control_size, "\n\n")

  cat("--- Losses ---\n")
  cat(sprintf("Total Loss: %.4f\n\n", loss))

  cat(sprintf("--- Local Balance (LSD) %s ---\n", "%"))
  cat(sprintf("Max LSD:   %.4f\n", lsd_train$lsd_max))
  cat(sprintf("Mean LSD:  %.4f\n\n", lsd_train$lsd_mean))
  
  cat(sprintf("--- Global Standardized Differences (GSD) %s ---\n", "%"))
  
  # Format for printing
  cov_names <- format(balance_table$Covariate, width = max(nchar(balance_table$Covariate)) + 2, justify = "left")
  pre_gsd_fmt <- format(sprintf("%.4f", balance_table$Pre_Weighting_GSD), width = 12, justify = "right")
  post_gsd_fmt <- format(sprintf("%.4f", balance_table$Post_Weighting_GSD), width = 12, justify = "right")
  
  # Header row
  cat(format("Covariate", width = max(nchar(balance_table$Covariate)) + 2, justify = "left"),
      format("Pre-GSD", width = 12, justify = "right"),
      format("Post-GSD", width = 12, justify = "right"), "\n")
  
  cat(strrep("-", max(nchar(balance_table$Covariate)) + 30), "\n")
  
  # Print each row
  for (i in seq_along(cov_names)) {
    cat(cov_names[i], pre_gsd_fmt[i], post_gsd_fmt[i], "\n")
  }
  cat("\n")

  cat("--- Treatment Effect Estimate ---\n")
  if (has_stored_effect && !is.null(effect)) {
    # Stored effect from Python path
    cat(sprintf("%s: %.4f", effect_label, effect))
    if (!is.null(se_val)) {
      cat(sprintf("  (SE: %.4f)", se_val))
    }
    if (!is.null(ci_lower) && !is.null(ci_upper)) {
      cat(sprintf("  95%% CI: [%.4f, %.4f]", ci_lower, ci_upper))
    }
    cat("\n")
  } else if (!is.null(effect)) {
    # R-based est_effect point estimate
    cat(sprintf("%s: %.4f (no variance estimate; computed via est_effect)\n",
                effect_label, effect))
  } else {
    cat("Effect estimate not calculated. Provide `Y` to compute a point estimate,\n")
    cat("or fit the model with `Y` inside `lbc_net()` to obtain effect and variance.\n")
  }
  
  # Return object
  summary_list <- list(
    sample_info = list(
      sample_size    = sample_size,
      treated_size   = treated_size,
      control_size   = control_size,
      num_covariates = num_covariates
    ),
    loss = loss,
    local_balance = list(
      lsd_max  = lsd_train$lsd_max,
      lsd_mean = lsd_train$lsd_mean
    ),
    balance_table    = balance_table,
    treatment_effect = if (!is.null(effect)) {
      list(
        type     = effect_label,
        estimate = effect,
        se       = se_val,
        ci_lower = ci_lower,
        ci_upper = ci_upper
      )
    } else {
      NULL
    },
    gsd = gsd_values_after
  )
  
  invisible(summary_list)

}

#' Summary of an lsd Object
#'
#' @description Provides a structured summary of an `lsd` object.
#'
#' @param object An object of class `"lsd"`, generated by `lsd()`.
#' @param ... Additional arguments passed to the specific method.
#'
#' @return A structured summary of the `lbc_net` object, including:
#' \itemize{
#'   \item Average local balance over all cks for each covariate.
#'   \item Local balance summary: `lsd_max`, `lsd_mean` for local standardized mean difference calculated during training.
#'   \item Sample characteristics: `sample_size`, `num_covariates`, `treated_size`, `control_size`.
#' }
#'
#' @details
#' The function extracts key model components using \code{\link{getLBC}}.
#'
#' @seealso \code{\link{getLBC}}
#'
#' @examples
#' \dontrun{
#' model <- lbc_net(data = data, formula = Tr ~ X1 + X2 + X3 + X4)
#' lsd_result <- lsd(model)
#' summary(lsd_result)
#' }
#'
#' @importFrom stats formula
#' @importFrom dplyr %>%
#' @export
summary.lsd <- function(object, ...) {
  if (!inherits(object, "lsd")) {
    stop("Error: `object` must be of class 'lsd'.")
  }

  # Extract key components using getLBC()
  LSD_mean <- getLBC(object, "LSD_mean")
  LSD_max <- getLBC(object, "LSD_max")
  LSD <- getLBC(object, "LSD")
  Z <- getLBC(object, "Z")
  Tr <- getLBC(object, "Tr")
  ATE <- getLBC(object, "ate_flag")

  # Compute sample characteristics
  sample_size <- nrow(Z)
  num_covariates <- ncol(Z)

  # Compute treatment group sizes
  treated_size <- sum(Tr)
  control_size <- sample_size - treated_size

  # Convert ATE integer to descriptive string
  ATE_label <- if (ATE == 1) "ATE (Average Treatment Effect)" else "ATT (Average Treatment Effect on the Treated)"

  # Print Summary
  # Format formula output
  formula_text <- deparse(formula, width.cutoff = 60)

  # Print Summary
  cat("Call:\n", formula_text, "\n")
  cat("Sample Size:", sample_size, " | Number of Covariates:", num_covariates, "\n")
  cat("Treated:", treated_size, " | Control:", control_size, "\n")
  cat("Estimand:", ATE_label, "\n\n")

  cat(sprintf("--- Local Balance (LSD) %s ---\n", "%"))
  cat(sprintf("Max LSD:   %.4f\n", LSD_max))
  cat(sprintf("Mean LSD:  %.4f\n\n", LSD_mean))

  # Convert LSD named vector to a dataframe
  lsd_df <- data.frame(
    Covariate = if (!is.null(colnames(LSD))) {
      colnames(LSD)
    } else {
      paste0("Z", seq_len(ncol(LSD)))  # Generate Z1, Z2, ..., Zp if colnames are NULL
    },
    LSD = sprintf("%.4f", as.numeric(colMeans(LSD)))
  )

  # Define column width for alignment
  max_name_length <- max(nchar(lsd_df$Covariate)) + 2  # Adjust spacing
  formatted_covariate <- format(lsd_df$Covariate, width = max_name_length, justify = "left")
  formatted_lsd <- format(lsd_df$LSD, width = 7, justify = "right")

  cat(format("Covariates", width = max_name_length, justify = "left"),
      format("LSD %", width = 7, justify = "right"), "\n")
  cat(strrep("-", max_name_length + 9), "\n")

  # Print table with proper alignment
  for (i in seq_along(formatted_covariate)) {
    cat(formatted_covariate[i], formatted_lsd[i], "\n")
  }

  cat("\n")

}

#' Summary of an lbc_net_surv Object
#'
#' @description
#' Provides a structured summary of an \code{"lbc_net_surv"} object,
#' including training loss, balance assessments, and the estimated survival
#' difference with standard error and confidence interval at a grid of time
#' points.
#'
#' @param object An object of class \code{"lbc_net_surv"}, generated by
#'   \code{\link{lbc_net_surv}}().
#' @param ... Additional arguments (ignored).
#'
#' @return A list containing:
#' \describe{
#'   \item{\code{sample_info}}{Sample sizes and covariate counts.}
#'   \item{\code{loss}}{Training loss.}
#'   \item{\code{local_balance}}{Local standardized differences (LSD) from training.}
#'   \item{\code{balance_table}}{Pre- and post-weighting global standardized
#'         differences (GSD).}
#'   \item{\code{survival}}{Estimated survival curves \eqn{S_1(t)}, \eqn{S_0(t)},
#'         survival difference, standard errors, and confidence intervals on
#'         the evaluation grid.}
#'   \item{\code{gsd}}{GSD after weighting.}
#' }
#'
#' @details
#' The function extracts key model components using \code{\link{getLBC}} from
#' the fitted object. It reports:
#' \itemize{
#'   \item Sample size and covariate dimensions;
#'   \item Training loss and local balance diagnostics (LSD);
#'   \item Global standardized differences (GSD) before and after weighting;
#'   \item The estimated survival difference \eqn{\Delta(t) = S_1(t) - S_0(t)}
#'         over the evaluation time grid, including standard errors and
#'         Wald 95\% confidence intervals.
#' }
#'
#' This method is specifically designed for survival outcomes fitted via
#' \code{\link{lbc_net_surv}}. For non-survival outcomes, use
#' \code{\link{summary.lbc_net}} instead.
#'
#' @seealso \code{\link{lbc_net_surv}}, \code{\link{gsd}}, \code{\link{getLBC}}
#'
#' @examples
#' \dontrun{
#'   fit_surv <- lbc_net_surv(
#'     data    = dat,
#'     formula = Tr ~ X1 + X2,
#'     time    = "time",
#'     delta   = "delta"
#'   )
#'   out <- summary(fit_surv)
#'   names(out)
#'   head(out$survival$survival_df)
#' }
#'
#' @export
summary.lbc_net_surv <- function(object, ...) {
  
  if (is.null(object) || !inherits(object, "lbc_net_surv")) {
    stop("Error: `object` must be an object of class 'lbc_net_surv'.")
  }
  
  ## 1. Extract main components via getLBC()
  loss      <- getLBC(object, "loss")
  lsd_train <- getLBC(object, "lsd_train")
  formula   <- getLBC(object, "formula")
  Z         <- getLBC(object, "Z")
  Tr        <- getLBC(object, "Tr")
  
  surv_obj <- getLBC(object, "survival")
  
  times    <- surv_obj$times
  S1       <- surv_obj$S1
  S0       <- surv_obj$S0
  diff     <- surv_obj$diff
  se_diff  <- surv_obj$se_diff
  ci_lower <- surv_obj$ci_lower
  ci_upper <- surv_obj$ci_upper
  
  ## 2. Sample characteristics
  sample_size    <- nrow(Z)
  num_covariates <- ncol(Z)
  treated_size   <- sum(Tr)
  control_size   <- sample_size - treated_size
  
  ## 3. GSD: before (weights = 1) and after weighting
  gsd_values_before <- gsd(Z = Z, Tr = Tr, wt = rep(1, sample_size))
  gsd_values_after  <- gsd(object)
  
  balance_table <- data.frame(
    Covariate          = names(gsd_values_after),
    Pre_Weighting_GSD  = as.numeric(gsd_values_before),
    Post_Weighting_GSD = as.numeric(gsd_values_after),
    row.names = NULL
  )
  
  ## --- Printing section ---
  
  formula_text <- deparse(formula, width.cutoff = 60)
  
  cat("Call:\n", formula_text, "\n")
  cat("Sample Size:", sample_size,
      "| Number of Covariates:", num_covariates, "\n")
  cat("Treated:", treated_size, "| Control:", control_size, "\n\n")
  
  cat("--- Loss ---\n")
  cat(sprintf("Total Loss: %.4f\n\n", loss))
  
  cat(sprintf("--- Local Balance (LSD) %s ---\n", "%"))
  cat(sprintf("Max LSD:   %.4f\n", lsd_train$lsd_max))
  cat(sprintf("Mean LSD:  %.4f\n\n", lsd_train$lsd_mean))
  
  cat(sprintf("--- Global Standardized Differences (GSD) %s ---\n", "%"))
  
  # Formatting for printing balance table
  cov_width   <- max(nchar(balance_table$Covariate))
  cov_names   <- format(balance_table$Covariate,
                        width = cov_width + 2, justify = "left")
  pre_gsd_fmt  <- format(sprintf("%.4f", balance_table$Pre_Weighting_GSD),
                         width = 12, justify = "right")
  post_gsd_fmt <- format(sprintf("%.4f", balance_table$Post_Weighting_GSD),
                         width = 12, justify = "right")
  
  # Header
  cat(format("Covariate",
             width = cov_width + 2, justify = "left"),
      format("Pre-GSD", width = 12, justify = "right"),
      format("Post-GSD", width = 12, justify = "right"),
      "\n")
  
  cat(strrep("-", cov_width + 30), "\n")
  
  # Rows
  for (i in seq_along(cov_names)) {
    cat(cov_names[i], pre_gsd_fmt[i], post_gsd_fmt[i], "\n")
  }
  cat("\n")
  
  ## --- Survival difference summary ---
  
  cat("--- Survival Difference Delta(t) = S1(t) - S0(t) ---\n")
  
  # Table of grid points
  n_grid <- length(times)
  cat("\nGrid of evaluation times:\n")
  if (n_grid <= 10L) {
    show_idx <- seq_len(n_grid)
  } else {
    show_idx <- seq_len(10L)
  }
  
  surv_tab_show <- data.frame(
    time    = times[show_idx],
    S1      = S1[show_idx],
    S0      = S0[show_idx],
    diff    = diff[show_idx],
    se      = se_diff[show_idx],
    ci_low  = ci_lower[show_idx],
    ci_high = ci_upper[show_idx]
  )
  
  print(surv_tab_show, row.names = FALSE)
  if (n_grid > 10L) {
    cat("... (showing first 10 of", n_grid, "time points)\n")
  }
  
  ## --- Return structured list ---
  
  survival_df <- data.frame(
    time    = times,
    S1      = S1,
    S0      = S0,
    diff    = diff,
    se      = se_diff,
    ci_low  = ci_lower,
    ci_high = ci_upper
  )
  
  summary_list <- list(
    sample_info = list(
      sample_size    = sample_size,
      treated_size   = treated_size,
      control_size   = control_size,
      num_covariates = num_covariates
    ),
    loss = loss,
    local_balance = list(
      lsd_max  = lsd_train$lsd_max,
      lsd_mean = lsd_train$lsd_mean
    ),
    balance_table = balance_table,
    survival = survival_df,
    gsd = gsd_values_after
  )
  
  invisible(summary_list)
}

